title: AuditFlow
description: Open-source Compliance-as-Docs engine. Bridging the gap between engineering and audit through formal mathematical verification.
theme: jekyll-theme-cayman

# SEO and Social Metadata
author: Sai Sravan Cherukuri & Sai Saketh Cherukuri
lang: en_US
twitter:
  username: AuditFlow_Project # Change this if you have a handle
  card: summary_large_image

# Plugins for Search Engines
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Internal Links
url: "https://saisravan909.github.io"
baseurl: "/AuditFlow"
